[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "book-renewer"
version = "0.1.0"
description = ""
requires-python = ">=3.13"


[tool.hatch.build.targets.wheel]
packages = ["src/app"]